version: "3"
services:
  mqtt:
    image: toke/mosquitto
    network_mode: bridge
    container_name: mqtt
    user: 1883:1883
    expose:
      - 8883
    ports:
      - 8883:8883
      - 9001:9001
    volumes:
      - ./config:/mqtt/config:ro
      - ./log:/mqtt/log
      - ./data:/mqtt/data
    restart: unless-stopped